In [128]:
import tensorflow as tf
tf.__version__

'2.3.0'

# Creating Tensors
1. List 
2. Array(numpy)  
3. TensorFlow

In [129]:
my_list = [1,2,3,4,5]
type(my_list)

list

In [130]:
# Converting Data Type to Tensor
tf_list = tf.convert_to_tensor(my_list,dtype = tf.float32)

In [131]:
tf_list

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [132]:
type(tf_list)

tensorflow.python.framework.ops.EagerTensor

#### Creating a multi-dimensional list

In [133]:
my_list = [[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5]]

In [134]:
tf_list1 = tf.convert_to_tensor(my_list, dtype = tf.float32)

In [135]:
print(tf_list)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [136]:
print(tf_list1)

tf.Tensor([[1. 2. 3. 4. 5.]], shape=(1, 5), dtype=float32)


In [137]:
my_list_col = [[1], [2], [3], [4], [5]]
tf_list2  = tf.convert_to_tensor(my_list_col, dtype = tf.float32)

In [138]:
print(tf_list2)

tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float32)


##### 2.  Converting Numpy Arrays to Tensor

In [139]:
import numpy as np

In [140]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [141]:
tf_arr = tf.convert_to_tensor(arr, dtype =tf.float32)
print(tf_arr)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


##### Creating a multi-dimensional array

In [142]:
# 2 x 2
arr1 = np.array([[1,2], [3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [143]:
type(arr1)

numpy.ndarray

In [144]:
tf_arr1 = tf.convert_to_tensor(arr1, dtype =tf.int64)

In [145]:
type(tf_arr1)

tensorflow.python.framework.ops.EagerTensor

In [146]:
print(tf_arr1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


##### 3. Constants

In [147]:
tf_const= tf.constant([1,2,3,4,5], dtype = tf.float32)
print(tf_const)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [148]:
tf_const1 = tf.constant(np.array([[1,2],[3,4]]))
tf_const1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

# TENSORFLOW OPERATORS

In [149]:
#Addition

x = tf.constant([[1,2,3]])
y = tf.constant([[4,5,6]])
print(x)
print(y)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[4 5 6]], shape=(1, 3), dtype=int32)


In [150]:
z = tf.add(x,y)
z

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 7, 9]])>

In [151]:
x1 = tf.constant(2)
x2 = tf.constant(3)

In [152]:
#Subtraction, Multiplication, Power
print(tf.subtract(x1,x2))
print(tf.multiply(x1,x2))
print(tf.pow(x1,x2))

tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [153]:
div = tf.divide(x1,x2)

In [154]:
print(div)

tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


# DataFlow Graphs

###### Steps in creating a TensorFlow Graph
1. create a tensorflow Function tf.function
2. Create a Writer 
3. add trace on function
4. Export the Graph

In [155]:
#1. Creating a Tensorflow function
def my_func(a,b):
    
    # Creating Constants(input nodes)
    x = tf.constant(a, dtype = tf.float32)  # Conversion into tensors
    y = tf.constant(b, dtype = tf.float32)  #Conversion into tensors

    # Operation(node)
    z = tf.add(x,y)
    return z


In [156]:
# Creating logdir
logdir = 'First_graph'
writer = tf.summary.create_file_writer(logdir = logdir)
# trace on function
tf.summary.trace_on(graph = True, profiler = True)
c = my_func(4,5) # Execute only once

with writer.as_default():
    tf.summary.trace_export('addition', step =0, profiler_outdir = logdir)

In [157]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 3A6F-D5E8

 Directory of C:\Users\hp\Desktop\MACHINE LEARNING

01/12/2022  11:16 AM    <DIR>          .
01/12/2022  11:16 AM    <DIR>          ..
01/10/2022  02:53 PM    <DIR>          .ipynb_checkpoints
01/10/2022  02:48 PM            88,096 Airports Analysis.ipynb
12/19/2021  02:35 PM        16,415,525 all_data
12/19/2021  02:56 PM        16,697,881 all_data.csv
12/23/2021  07:13 PM           621,113 BASE TRAVELLING COST PREDICTION .ipynb
12/23/2021  07:28 PM           629,656 BASE TRAVELLING COST PREDICTION -Copy1.ipynb
01/04/2022  09:05 PM           555,303 BASE TRAVELLING COST PREDICTION -Copy2.ipynb
11/15/2021  06:57 AM            78,846 Clustering Data.csv
11/18/2021  08:00 PM           186,413 Clustering Project.ipynb
12/01/2021  11:26 AM    <DIR>          DATA FOR ZINDI COMPETITION
01/12/2022  11:16 AM    <DIR>          First_graph
12/02/2021  06:02 PM                 0 geckodriver.log
11/21/2021  09:01 AM            74

In [158]:
ls First_graph


12/20/2021  08:04 PM            30,643 submission_new2.csv
12/20/2021  08:06 PM            30,645 submission_new3.csv
12/20/2021  08:12 PM            23,749 submission_new4.csv
12/06/2021  02:01 PM            29,120 TRAVELLING COST PREDICTION -Copy1.ipynb
12/20/2021  08:22 PM         4,044,822 TRAVELLING COST PREDICTION -Copy2.ipynb
11/29/2021  04:06 PM            55,725 UNDERSTANDING PANDAS.ipynb
11/18/2021  01:46 PM           174,656 Untitled.ipynb
12/02/2021  07:41 PM             6,771 Untitled1.ipynb
12/22/2021  05:07 PM                72 Untitled2.ipynb
12/23/2021  07:12 PM            98,423 Untitled3.ipynb
01/10/2022  02:49 PM             5,381 Untitled4.ipynb
              29 File(s)     40,930,721 bytes
               7 Dir(s)  319,672,872,960 bytes free
 Volume in drive C has no label.
 Volume Serial Number is 3A6F-D5E8

 Directory of C:\Users\hp\Desktop\MACHINE LEARNING\First_graph

01/12/2022  11:16 AM    <DIR>          .
01/12/2022  11:16 AM    <DIR>          ..
01/12/2022

In [159]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [160]:
%tensorboard --logdir First_graph/

Reusing TensorBoard on port 6006 (pid 3584), started 1 day, 19:24:15 ago. (Use '!kill 3584' to kill it.)

#### Graph 2

In [161]:
def second_graph(a,b,c):
    # Create the imput layer
    x1 = tf.constant(a, dtype= tf.float32)
    x2 = tf.constant(b, dtype = tf.float32)
    x3 = tf.constant(c, dtype = tf.float32)

    #Layer 1
    layer_1_add = tf.add(x1, x2)
    layer_1_sub=  tf.subtract(x1, x3)

    #layer 2
    layer_2_sub = tf.negative(layer_1_add)
    layer_2_mult = tf.multiply(layer_1_add, x2)
    layer_2_add = tf.add(layer_1_add, x3)

    #Output Layer
    output = tf.add(layer_2_add, tf.add(layer_1_sub, (layer_1_sub, tf.add(layer_2_sub, layer_2_mult))))
    return output

In [163]:
#logdir
writer = tf.summary.create_file_writer('./graphs')
#trace on
tf.summary.trace_on(profiler  =True, graph= True)
out = second_graph(4,5,6) #exceute only once

with writer.as_default():
    tf.summary.trace_export(name = 'Second Graph', step =0, profiler_outdir='./graphs')



In [164]:
%reload_ext tensorboard

In [165]:
%tensorboard --logdir ./graphs

ERROR: Timed out waiting for TensorBoard to start. It may still be running as pid 14104.